---
- project:
    check:
      jobs:
        - openstack-tox-linters
        - k8sapp-istio-tox-py39
        - k8sapp-istio-tox-pylint
        - k8sapp-istio-tox-flake8
        - k8sapp-istio-tox-metadata
    gate:
      jobs:
        - openstack-tox-linters
        - k8sapp-istio-tox-py39
        - k8sapp-istio-tox-pylint
        - k8sapp-istio-tox-flake8
        - k8sapp-istio-tox-metadata
    post:
      jobs:
        - stx-app-istio-upload-git-mirror

- job:
    name: k8sapp-istio-tox-py39
    parent: tox-py39
    description: |
        Run py39 for istio app
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    files:
      - python3-k8sapp-istio/*
    vars:
        tox_envlist: py39
        python_version: 3.9
        tox_extra_args: -c python3-k8sapp-istio/k8sapp_istio/tox.ini
        tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: k8sapp-istio-tox-metadata
    parent: tox
    description: |
      Run metadata test for k8sapp_istio
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    vars:
      tox_envlist: metadata
      tox_extra_args: -c python3-k8sapp-istio/k8sapp_istio/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: k8sapp-istio-tox-pylint
    parent: tox
    description: |
      Run pylint test for k8sapp_istio
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    files:
      - python3-k8sapp-istio/*
    vars:
      tox_envlist: pylint
      tox_extra_args: -c python3-k8sapp-istio/k8sapp_istio/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: k8sapp-istio-tox-flake8
    parent: tox
    description: |
      Run flake8 test for k8sapp_istio
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    files:
      - python3-k8sapp-istio/*
    vars:
      tox_envlist: flake8
      tox_extra_args: -c python3-k8sapp-istio/k8sapp_istio/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: stx-app-istio-upload-git-mirror
    parent: upload-git-mirror
    description: >
      Mirrors opendev.org/starlingx/app-istio to
      github.com/starlingx/app-istio
    vars:
      git_mirror_repository: starlingx/app-istio
    secrets:
      - name: git_mirror_credentials
        secret: stx-app-istio-github-secret3
        pass-to-parent: true

- secret:
    name: stx-app-istio-github-secret3
    data:
      user: git
      host: github.com
      # yamllint disable-line rule:line-length
      host_key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
      ssh_key: !encrypted/pkcs1-oaep
        - ibtpD7VQ74t/7AzieVCein/jr8ZdGKVihCRi7UVMlbsWaz2DZB63Z0Pp52ERyAcXXjwDm
          fdvWDHa6ziP9+h5M8hHO6v3nn/b5Cwf+X440v/hLAwp9oPwPT8A3LuboHA907t2Koc1HA
          bk6nYU36qaJe630WrG6dhWUyAcDMYfn07jSqVeTfxIJHibWrC//WBw1YpvfwVz2xTMyim
          h67ogtX8EYsgWnpuMFMepg5ZU78BcnCGZ5GO5r2Q5djSLW18RbxD9QO6EsJYBxNA2x6FN
          VHgTf725LPEccGcFfUiQBtviP1Pm+XevBshGRdoqSJFO5eG6guXUVafiQ6+Euq4KTwIUU
          0L/xkAqOH4ckkLdbqSYY+QAKLhKHIyDqxQVkK5QVTUyKifVHDkz4LwqF3EVXLeRV5+Zdj
          DzoSWkpBStjV/f6hFTZ59NsSdbP7jsKXE39CRD1xC2BchVh2Ed2YaSEN2hA8W1bs608UR
          V5hvGb4w/lI8FEVEBm1A+oJd78CJA2PoYSOcSPfJG9W7lHlOD709aj0ctOZYJ2suWaAcN
          r2QFOfmSYF4x6+/OhabXWfTLzSctfK2VLvygAPIHGMZwQyNwkWQ9TbiCOUqXT4gFkc8jB
          IxjP725kXyoxJ6O7cHviTkcUP/FyovkhwHcOZ/SadWVROqrCMPuqxnXEiQFR/Y=
        - hoeLDsgrlJhZ+Dyrr7hXmFWlllnLB6i7fX/QpYM569qhzpku7WIh8v9Mj880Nk4W0VNV6
          NsKMe5y6xCMa74tiyGhaAx2IP5MrmJRnovYwQRz/AuLbiaFiSrNgJR0LvDKaOZc3S2VQt
          0wXNnk3XtAId35rfjE4ZPL+LhBRQIEKUdKsIJhWaZF4jQm+sHg4GJ4JXbpAG9DKHQBY0L
          A+8CKVB/PN87/7m5yVOv2tdM6ULL2YcXurgEaureamTr85oGC2bZBihK/JhqkoeOVDqcA
          jhyoseF1DkQ5FrOgHiJflsLj5848QdLTZsM9wcOaFORmKYkbzGewPns0v1wNHT/j7Vxq5
          Yd9UPz3ODSqKYsopjtfS4tcP0QDliSdlXyIzhQZJcIdH0uN2+84i7o35pYotzbW8Gha1R
          9/XWRhhh2bm3+H54xii2GZ4kek2TTJGo9rSb1eUvlA9gXzYoQ2ON4PuCDbz+eRUqQbQGX
          Poio2ZmtVT1+Zwmt8Axi9vvkRF4BwU/VrEfRjr3gCEiHAEl+SI9j6mUvl67fd4ILEunt3
          C/QACwhd24XxYZRHzm67qYTWQu7Eb4lzAgzg5r/KrGMNNHMO7eZnRyQPXXykLZLN/quhW
          hMMStc2FK+4ZkWXd1UiuIjOtWxkDa8GcuLO3VFnJ/DgO0b4a9iQpnKXe170gEQ=
        - atnEZ42DlJeTwrUxS6onVXYmT2FbnAKgCLOZ7P7dNQTwgeJxgZqDf04O2ExCRFwIRI9/U
          fItShcSe+zBJ5/A2KmcuALkMt4tqXBRZckuQ0JzPS6OFRRK0EsKpj/1VRvVQLVA+JAZSD
          17k8M64hYtqw9SvLgo4/3Zy5i5MOfkrWoYJpT3JJyd/hl4wsBKF6zutEfNNbikl+XcXir
          9qFz2eDkPuyAb1RjqKgEEEo1vRAmCrV1WkAKWJbgjXgBTLGXzv0cS9jgvnibzQrrVUvy5
          dpPMyMoOxH3IaO8j8dkpRL/gA0FU1OtZMUZIe0YsAgAESnj3r8Q+WI4HEFyczDmPqpUY2
          67pOs66nUVy9vMNSPS3yV/nFBkzBcBBDBsoUVvYmCyAYNEIMPoBwpt732Tck89h+vGrQX
          5tFVqwDemv/icV2iZnO9+lpRzsaBiBM4KDR8ozoZH6Y9eL2/CEC6ScgAuxSpLDM0za+Pf
          Lp7RTpbRrRUDkID4EMpiUAZdB8g1K9MnGfrOc+46djZYIZ4EYQC8sLVYJlU51PJCNioYE
          JSKenpLg9w+0U2j7M77GXPsDLmX/n5hu9LZ4YLnPyXJV3V/nOhZpy8aFlqxGSpRPEjJ49
          jrRHqRg/6ZCRbsZ3gJ11wYdm0XHx4BfjXNR8BV1RvkoYV3Qx1T6IQbeQmgZB5Q=
        - d0aTfXvSFiCarGppk3ansEEZdrglwV4I8MZqHA4Oz8uLifoNNc7Ov4wj7WehjgiEOLCbG
          VOLeoamCmhmwuUAJj+soa1ab0rGy7L7op9pbrYG2d90zCSFBHc7FSg3r4Yc1uB/2t1KYJ
          86GJJ2PQt1ceuJaYJBsjKenb4emlDEmsmlt6WMKZkg9jzOW28VWXwbYCMRJ+9fXOXRz3p
          MUft9FoAdt6hAZ2+tcQHmok2790A1Weo5ioCsukZSJdLKyqb1pkwQX6k05Hlfz8lLua2l
          Szuh08fsuIyhZdD/Q4qYX7lO4qM1J7j0jGwYq7dttn3+nMsGXeIqLG2f4IM8iZu0zv9oZ
          hA8YLs0JR0px0dWGYxDmLpMEwt09xdyZRcEIw+8frPDeje480zXzKghrTn3xWFYqmdwMv
          eYE4KxE1bRXbbyhgpUHZ03MS0xyU2frtDzajX8Dytwi3jtJN4xI+HmLR/Fs0gzr6VxOq5
          jmnQ0yhpOnO5LyTK9K6lVlt4YSuW+KzCJN0hm51M1vPGdENKIiUAIS5u/49z38f9HwvRd
          Ex6c8TiyyuOrHQnwB0J+NHMCLiATsrCAOnAZiIR0dKLbxC89OsSD1CLDZm2icTwq+r5Ej
          E4svBwR5q6h6guh64niX8JhGeBVPLyQfCiu5RKUPI9oIUXaZ43wYa1RoamsoFA=
        - afI9nRV2WoCW4KO31EvD1aIjCSWVepOfkY+fLoxjuP7BHtIodSOHzzgZ8liUW7I6HpSje
          U7vqjO9BXPro4O093k1pQAuLSqm9gOo4RNnTXYumm0KisIIVcOQ+YHcT0PHrlqW3wJjfv
          2WCkrVMzdki+YVaMXhJ8iRP27PwwQ+hLh0CiSJsaFK2rbPbX8vlXXH9BKuEDIl2nugNyw
          6zSC3dC/GI3asRPkyqLo85sqVLTlknsecbVsGPLy5ZghV7J7Tp7zG7xgUeDAcw6VnI0D4
          TN4Klf9wBP1Zglq3VQqvQcKENXwxJNsyeswho1LNA3yQmiEZ/MADVFgRGwnY8DL2SDMd2
          KJUUUoMHuVYdDEpPTw4PLuqvMhOb1GZHWfOWxSUSukZu5mf/hwHUlA4qiTI2v0A8zljdZ
          3hxzKAYgF0mqoDhQHflN6QlSmK+GbpXPs4c4Kfq3uI+K4U7mbFuhohj1iJAWWOP7eZvjY
          cnliFIhtYWu1dUIjP3nwzgYNeKG/SsAoU4FetzsPNe9CKUuk68zaiATg6OjXogPqVCUy3
          +GG+5/bKZIERZu1uccNfITxu/P3fyn45wNl47+m8H3TY//5167xTdFthiCoI6DlJZE4QV
          6R+d8LEpBCJlQsytNTvDA+JaCD7Mg5uyJXK6Rtc7Dh6YT1Q1h1IKX5WOv9G72k=
        - Y0FKc6Akwa0eRffJ+IlWl5sqwWaJSUbnuIC0F96hiCsu3gD2/kmP4PmhfFezbnU3U/Djy
          Btmued/rw1YHa0UXGX4NEV84eoqQ3slPRwRNMOmJYSezUKGrEDTjpCoqqb+glektBSfZp
          zeZqmIhQ4QF0MlvtwN648zZjPmxUEnV/+/7VvL3FNZgRxjra3IzB9tSwBYuvxYBmGG91g
          L4ee+WOxU2GPu+9DgMytfJCGqKayUqWhHpp5BtgBzob9OSzEsX2g4eYvYXXCqEKhDCQlx
          KeTmL5N0QacLoEL/PP8NVtYnHYM4zkWtSyHBIXD6KMPwSjJ/5imcecCnO43LDdzuco476
          7mN+4WvF09ewZrS0UJ53a/b+cfHPj/B1XwNZxET4ygdTXnFpBJD4qQK7cxWWjnPFQm2Km
          MomAfPcPk1ZbJSZjJ7uOwOF4j/vlVKObfp9HNgoLxtpTvVUr0DqpPpCtiIH5p43cCwFhl
          dDDDX2AyY90WkSUUV60/MuCs6lHrsXUeQjjG5j7/KA5wO2QQ7j6t0/IAlK9dxtCy+XNr2
          jtqoBxMaxB2gb/5z1uNDgSVVmBaUIibcW8sv8Tnegs/xU/9uahYhP09OjuJFruZGMj2mG
          intrmRWftb0vAS7mCb3q3nCPmDSSZdABZiB+zXX/POWuvOMeXWRZsBu4KQEMWg=
        - OJ/ZtbdOHwHXbiy0wxCxZ5sVzM06XoeJ+UmymETkCYDxKl1pUycdRrBpBi0Y5efjnD59H
          A9EeCbQ3kB5/l8zDXdQVxC1xuHND+MN4qVGzxbi86mz4l9SoFQ+Nv40sfXkndfPFYVUYn
          Vm4lMkPfR4aFYdARK/kcRdf6jaKMlQ082PacLUjBpYlfcHdc1qHptEMrq1tvcqrGT6Znf
          wW+twy+WzI/RvCzZLQ1He65TtBHAx+JrUl6+M6R6JEf9eDHptsqNoMFDZq51mmm/fsIIy
          vSEONFSmRtEQkR/jQAvc4qjs/2rITMIeUHenPZ+2M2ke3UlFQb3XKtGFLv2Ceqo9nWfgD
          3LHRsqqdW6rko0nwdd2NkUZu8rk8Hp1+YbLSZHuCvhVd+gPFsW1ZTadNhLKBEtj6Y70Ni
          1DynFO6ErMp86yYQpCF/SHguomjU11+LNKgaSfOS3HCgUYkHl3asLN1boYLQEvUwxWts2
          JTpwSyJxpooTQLQ/Aj/3NJSfvq3DE4q02FzW0uwE6uBSn3SnPOuKjTmCVMy9M3udeTZFv
          zL/lcexzh1W8/671swqWlzM7r/2YsziXfC7QDrbhnoDQkbsgyNMJ7bRihzgLU9G9a3zqZ
          Scv6hS/yx4BJ1+snaKXS7bnHBGeAnluevQw197b4D0Y6l5zsq8trl2rVq4rgUk=
