[metadata]
name = k8sapp-istio
summary = StarlingX sysinv extensions for istio
long_description = file: README.rst
long_description_content_type = text/x-rst
license = Apache 2.0
author = StarlingX
author-email = starlingx-discuss@lists.starlingx.io
home-page = https://www.starlingx.io/
classifier =
    Environment :: OpenStack
    Intended Audience :: Information Technology
    Intended Audience :: System Administrators
    License :: OSI Approved :: Apache Software License
    Operating System :: POSIX :: Linux
    Programming Language :: Python
    Programming Language :: Python :: 2
    Programming Language :: Python :: 2.7
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.4
    Programming Language :: Python :: 3.5

[files]
packages =
    k8sapp_istio

[global]
setup-hooks =
    pbr.hooks.setup_hook

[entry_points]
systemconfig.helm_applications =
    istio = systemconfig.helm_plugins.istio

systemconfig.helm_plugins.istio =
    001_base = k8sapp_istio.helm.istio_base:IstioBaseHelm
    002_cni = k8sapp_istio.helm.istio_cni:IstioCniHelm
    003_istiod = k8sapp_istio.helm.istio_pilot:IstioPilotHelm
    004_istio-ingress = k8sapp_istio.helm.istio_ingressgateway:IstioIngressGatewayHelm
    005_istio-egress = k8sapp_istio.helm.istio_egressgateway:IstioEgressGatewayHelm
    006_kiali-server = k8sapp_istio.helm.kiali_server:KialiHelm

systemconfig.fluxcd.kustomize_ops =
    istio = k8sapp_istio.kustomize.kustomize_istio:IstioFluxCDKustomizeOperator

systemconfig.app_lifecycle =
    istio = k8sapp_istio.lifecycle.lifecycle_istio:IstioAppLifecycleOperator

[bdist_wheel]
universal = 1
