#
# Copyright (c) 2025 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

namespace: istio-system
resources:
  - helmrelease.yaml
secretGenerator:
  - name: istio-pilot-static-overrides
    files:
      - istio-pilot-static-overrides.yaml
  - name: istio-pilot-system-overrides
    files:
      - istio-pilot-system-overrides.yaml
generatorOptions:
  disableNameSuffixHash: true