#
# Copyright (c) 2025 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
resources:
  - base
  - istio-base
  - istio-cni
  - istio-pilot
  - istio-ingressgateway
  - istio-egressgateway
  - kiali-server
